"""Add extracted text to resume

Revision ID: f6fac867634f
Revises: ab6f4e7c7d6f
Create Date: 2026-08-01 15:13:32.147045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fac867634f'
down_revision: Union[str, Sequence[str], None] = 'ab6f4e7c7d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'extracted_text')
    # ### end Alembic commands ###
